# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-OpenID-Consumer
version:      0.06
version_from: lib/Net/OpenID/Consumer.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    URI:                           0
    URI::Fetch:                    0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
